worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name  localhost;

        location /api/ {
            proxy_pass http://backend:8080/;
        }

        location / {
            proxy_pass http://frontend:3000/;
        }

        error_page 502 503 504 /50x.html;
        location = /50x.html { root /usr/share/nginx/html; }
    }
}
